2022-02-25 20:46:32,366 INFO connect mongodb with some insecurity
2022-02-25 20:46:32,678 INFO Successfully connected with mongodb
2022-02-25 20:46:32,678 INFO try to create db carbon_nano_tube
2022-02-25 20:46:32,679 INFO check db exist carbon_nano_tube
2022-02-25 20:46:33,522 INFO Already exist db carbon_nano_tube
2022-02-25 20:46:33,522 INFO try to connecting db carbon_nano_tube
2022-02-25 20:46:33,522 INFO check db exist carbon_nano_tube
2022-02-25 20:46:33,602 INFO Successfully connected with db carbon_nano_tube
2022-02-25 20:46:33,602 INFO try to connect collection carbons_nano_coll
2022-02-25 20:46:33,675 INFO list of collection ['carbons_nano_coll']
2022-02-25 20:46:33,744 INFO avail this collection carbons_nano_coll
2022-02-25 20:46:33,744 INFO try to update data
2022-02-25 20:46:33,829 INFO data is updated <pymongo.results.UpdateResult object at 0x00000244EBADF2C0>
